services:
  ollama-model:
    image: ollama/ollama:0.6.5
    container_name: ollama_container
    ports:
      - "11434:11434"
    deploy: # according to instruction: https://docs.docker.com/compose/how-tos/gpu-support/
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # use `all` for all GPUs or `1` for one GPU
              capabilities: [ gpu ]
    command: serve
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      OLLAMA_MODEL_NAME: tinyllama
    pull_policy: missing
    restart: no
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
